version: '3.8'
services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://backend:5000

  admin:
    build:
      context: ../admin-dashboard
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - API_URL=http://backend:5000

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=mysql
      - REDIS_HOST=redis
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=tweepsweb@2025
      - MYSQL_DATABASE=tweepsdb
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:6.2-alpine
    volumes:
      - redis-data:/data

volumes:
  mysql-data:
  redis-data:
